arenadata: modify build scripts
- go binary was bumped to 1.20.5
- directory to store go binaries was changed: instead of ~/go (GOPATH)
  directory /opt/go uses to untar go archive. It's done due to
  compilation errors (`unkeyed fields at composite literals`, here is a
  link to stackoverflow: https://stackoverflow.com/questions/54548441/composite-literal-uses-unkeyed-fields)
  occured at unit-test stage (restore tets), after merging with
  upstream code, like:

  ```bash
  #> PATH=$PATH:~/go/bin GOPATH=~/go ginkgo restore
  Failed to compile restore:
  # github.com/greenplum-db/gpbackup/restore_test
  ./wrappers_test.go:168:54: github.com/greenplum-db/gpbackup/history.RestorePlanEntry struct literal uses unkeyed fields
  ./wrappers_test.go:194:54: github.com/greenplum-db/gpbackup/history.RestorePlanEntry struct literal uses unkeyed fields
  ```

  The error occurs at next (strange) condition: when go binary stores at
  GOPATH directory (untar was performed to GOPATH). Seems it's a golang
  issue (further research is needed)